FROM python:3.11-slim

WORKDIR /app

# Systempakete für Requests, SSL etc.
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

# Requirements installieren
COPY requirements-backend.txt .
RUN pip install --no-cache-dir -r requirements-backend.txt

# App-Code kopieren
COPY backend/ .

EXPOSE 5008

CMD ["python3", "playingonsonos.py"]
